code overhaul. tested and working.

diff --git a/FaceOff b/FaceOff
--- a/FaceOff
+++ b/FaceOff
@@ -28,133 +28,115 @@ bold=$(tput bold)
 normal=$(tput sgr0)
 
 ################################################################################
-
-function Help() {
-    cat <<HELP
-
-Usage:
-
-$(basename $0) ${bold}-i${normal} T1w_image.nii.gz ${bold}-n${normal} number of threads ${bold}-s${normal} use SyN
-
---------------------------------------------------------------------------------
-Input arguments:
-
-     -i:  T1w input dataset (e.g. T1w.nii.gz)
-
-     -n:  number of threads (default = 12)
-
-     -s:  (optional) use additional SyN stage (default = 0)
-
---------------------------------------------------------------------------------
-
-Example:
-
-$(basename $0) -i T1w.nii.gz -n 12
-
---------------------------------------------------------------------------------
-Script was created by: Sriranga Kashyap (03-2020)
---------------------------------------------------------------------------------
-Requires ANTs to be installed and $ANTSPATH defined in your environment.
---------------------------------------------------------------------------------
-ANTs can be downloaded here: https://github.com/ANTsX/ANTs
-References:
-    1) http://www.ncbi.nlm.nih.gov/pubmed/20851191
-    2) http://www.frontiersin.org/Journal/10.3389/fninf.2013.00039/abstract
---------------------------------------------------------------------------------
-
-HELP
-    exit 1
+# Define help message
+function usage {
+    echo "Usage: $(basename $0) [-h] -i <input_file> [-n <n_threads>] [-s <force_syn>]"
+    echo " "
+    echo "Options:"
+    echo "  -h                           Show this help message and exit."
+    echo "  -i <input_file>              Specify the input file for processing. (required)"
+    echo "  -n <n_threads>               Specify the number of threads for processing. Default: 1."
+    echo "  -s <force_syn>               Specify whether to force the SyN step of ANTS registration. Default: 0."
+    echo ""
+    echo ""
+    echo -e "Script was created by: Sriranga Kashyap (03-2020)\n"
+    echo -e "Requires ANTs to be installed and \$ANTSPATH defined in your environment\n"
+    echo -e "ANTs can be downloaded here: https://github.com/ANTsX/ANTs\n"
+    echo "Cite: "
+    echo "(1) http://www.ncbi.nlm.nih.gov/pubmed/20851191"
+    echo "(2) http://www.frontiersin.org/Journal/10.3389/fninf.2013.00039/abstract"
 }
 
 ################################################################################
-
 function reportParameters() {
-    cat <<REPORTPARAMETERS
-
---------------------------------------------------------------------------------
-    ${bold} 0. Initialised with $n_threads threads ${normal}
---------------------------------------------------------------------------------
-    ANTs installation found :   ${bold} $ANTSPATH ${normal} 
-    FaceOff location        :   ${bold} $SCRIPT_DIR ${normal}
-    Input data              :   ${bold} $input_file ${normal}
-    Using SyN?              :   ${bold} $syn ${normal}
-    Deface mask (output)    :   ${bold} $OUTPUT_MASK_NAME ${normal}
-    Defaced data (output)   :   ${bold} $OUTPUT_NAME ${normal}
---------------------------------------------------------------------------------
-
-REPORTPARAMETERS
+    echo "--------------------------------------------------------------------------------"
+    echo "  ${bold} 0. Initialised with $n_threads threads ${normal}"
+    echo "--------------------------------------------------------------------------------"
+    echo "  ANTs installation found :   ${bold} $ANTSPATH ${normal}"
+    echo "  FaceOff location        :   ${bold} $SCRIPT_DIR ${normal}"
+    echo "  Input data              :   ${bold} $input_file ${normal}"
+    echo "  Using SyN?              :   ${bold} $syn ${normal}"
+    echo "  Deface mask (output)    :   ${bold} $OUTPUT_MASK_NAME ${normal}"
+    echo "  Defaced data (output)   :   ${bold} $OUTPUT_NAME ${normal}"
+    echo "--------------------------------------------------------------------------------"
 }
-
-################################################################################
-
-if [[ "$1" == "-h" || $# -eq 0 ]]; then
-    Help >&2
-fi
-
-################################################################################
-#
-# DEFAULTS
-#
-################################################################################
-
-interpolation_type=GenericLabel
-n_threads=12
 
 ################################################################################
 #
 # PARSE INPUT ARGUMENTS
 #
 ################################################################################
-
-while getopts "h:i:n:s:" OPT; do
-    case $OPT in
-    h) #help
-        Help
+# Parse command-line arguments
+while getopts "h:i:n:s:" opt; do
+    case $opt in
+    h)
+        usage
         exit 0
         ;;
-    i) # input
+    i)
         input_file=$OPTARG
         ;;
-    n) # transformation type
+    n)
         n_threads=$OPTARG
         ;;
-    s) # force syn step
+    s)
         force_syn=$OPTARG
         ;;
-    \?) # report error
-        echo "$HELP" >&2
+    \?)
+        echo "Invalid option: -$OPTARG" >&2
+        usage
         exit 1
         ;;
     esac
 done
+
+# Check if any arguments were provided
+if [ $# -eq 0 ]; then
+    echo "Please specify at least input argument."
+    usage
+    exit 1
+fi
 
 ################################################################################
 #
 # SET NUMBER OF THREADS
 #
 ################################################################################
-
-ORIGINALNUMBEROFTHREADS=${ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS}
-ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$n_threads
-export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS
-
-################################################################################
-#
-# NO COMPRESSION PERHAPS
-#
-################################################################################
-
-if [ "${input_file#*.}" == "nii" ]; then
-
-    OUTPUT_MASK_NAME=${input_file%.*}_defaceMask.nii
-    OUTPUT_NAME=${input_file%.*}_defaced.nii
-
+if [ -n "$ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS" ]; then
+    n_threads=$ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS
 else
-
-    OUTPUT_MASK_NAME=${input_file%.*.*}_defaceMask.nii.gz
-    OUTPUT_NAME=${input_file%.*.*}_defaced.nii.gz
-
+    n_threads=12
+    ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$n_threads
+    export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS
 fi
+
+################################################################################
+#
+# FUNCTIONS
+#
+################################################################################
+if [[ ! "$input_file" == *\/* ]]; then
+    input_file="$PWD/${input_file}"
+fi
+
+function remove_extension() {
+    filename=$1
+
+    if [[ "$filename" == *.nii.gz ]]; then
+        new_filename="${filename%.nii.gz}"
+    elif [[ "$filename" == *.nii ]]; then
+        new_filename="${filename%.nii}"
+    else
+        echo "Error: invalid filename extension"
+        return 1
+    fi
+
+    echo $new_filename
+}
+
+OUTPUT_PREFIX=$(remove_extension $input_file)
+OUTPUT_MASK_NAME=${OUTPUT_PREFIX}_defaceMask.nii.gz
+OUTPUT_NAME=${OUTPUT_PREFIX}_defaced.nii.gz
 
 if [ -z "$force_syn" ]; then
     force_syn=0
@@ -176,57 +158,43 @@ reportParameters
 # MAP TO TEMPLATE
 #
 ################################################################################
-
 start_time0=$(date +%s)
 
 ${ANTSPATH}/antsAI \
     --dimensionality 3 \
-    --random-seed 42 \
+    --random-seed 13 \
     --transform AlignCentersOfMass \
     --metric MI[ $TEMPLATE_DIR/OASIS_T1w.nii.gz , $input_file , 32 , Regular , 0.25 ] \
     --output $TEMPLATE_DIR/REG_INPUT_TO_TEMP_INIT.mat
+
+ants_reg_affine='${ANTSPATH}/antsRegistration --verbose 0 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [ $TEMPLATE_DIR/REG_INPUT_TO_TEMP_, 1 , 1 ] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [ 0.005,0.995 ] -x [ $TEMPLATE_DIR/OASIS_registrationMask.nii.gz, 1 ] --initial-moving-transform [ $TEMPLATE_DIR/OASIS_T1w.nii.gz,$input_file,1 ] --transform Rigid[ 0.1 ] --metric MI[ $TEMPLATE_DIR/OASIS_T1w.nii.gz,$input_file,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox --transform Affine[ 0.1 ] --metric MI[ $TEMPLATE_DIR/OASIS_T1w.nii.gz,$input_file,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox'
+
+ants_syn_addon=' --transform SyN[ 0.1,3,0 ] --metric CC[ $TEMPLATE_DIR/OASIS_T1w.nii.gz , $input_file , 1 , 2 ] --convergence [ 50x25,1e-6,10 ] --shrink-factors 2x1 --smoothing-sigmas 1x0vox'
 
 if [ $force_syn -eq 1 ]; then
     echo "  ${bold} Additional SyN stage will be used. ${normal}"
     echo " "
 
-    ${ANTSPATH}/antsRegistration \
-        --verbose 0 \
-        --random-seed 42 \
-        --dimensionality 3 \
-        --float 0 \
-        --collapse-output-transforms 1 \
-        --output [ $TEMPLATE_DIR/REG_INPUT_TO_TEMP_ , 1 , 1 ] \
-        --interpolation BSpline[4] \
-        --use-histogram-matching 1 \
-        --winsorize-image-intensities [ 0.005,0.995 ] \
-        --masks [ $TEMPLATE_DIR/OASIS_registrationMask.nii.gz , 1 ] \
-        --initial-moving-transform $TEMPLATE_DIR/REG_INPUT_TO_TEMP_INIT.mat \
-        --transform Rigid[ 0.1 ] \
-        --metric Mattes[ $TEMPLATE_DIR/OASIS_T1w.nii.gz , $input_file , 1 , 32 , Regular , 0.25 ] \
-        --convergence [ 1000x500x250,1e-6,10 ] \
-        --shrink-factors 4x2x1 \
-        --smoothing-sigmas 3x2x1vox \
-        --transform Affine[ 0.1 ] \
-        --metric Mattes[ $TEMPLATE_DIR/OASIS_T1w.nii.gz , $input_file , 1 , 32 , Regular , 0.25 ] \
-        --convergence [ 1000x500x250,1e-6,10 ] \
-        --shrink-factors 4x2x1 \
-        --smoothing-sigmas 3x2x1vox \
-        --transform SyN[ 0.1,3,0 ] \
-        --metric CC[ $TEMPLATE_DIR/OASIS_T1w.nii.gz , $input_file , 1 , 2 ] \
-        --convergence [ 50x25,1e-6,10 ] \
-        --shrink-factors 2x1 \
-        --smoothing-sigmas 1x0vox
+    ants_cmd="$ants_reg_affine$ants_syn_addon"
+    eval $ants_cmd
 
     echo "  ${bold} 1. Mapped to template.    ${normal}"
     echo "--------------------------------------------------------------------------------"
 
-    ################################################################################
-    #
-    # APPLY TRANSFORMS
-    #
-    ################################################################################
+else
+    ants_cmd="$ants_reg_affine"
+    eval $ants_cmd
 
+    echo "  ${bold} 1. Mapped to template.    ${normal}"
+    echo "--------------------------------------------------------------------------------"
+fi
+
+################################################################################
+#
+# APPLY TRANSFORMS
+#
+################################################################################
+if [ $force_syn -eq 1 ]; then
     ${ANTSPATH}/antsApplyTransforms \
         --dimensionality 3 \
         --interpolation GenericLabel \
@@ -239,41 +207,7 @@ if [ $force_syn -eq 1 ]; then
 
     echo "  ${bold} 2. Deface mask created.    ${normal}"
     echo "--------------------------------------------------------------------------------"
-
 else
-
-    ${ANTSPATH}/antsRegistration \
-        --verbose 0 \
-        --random-seed 42 \
-        --dimensionality 3 \
-        --float 0 \
-        --collapse-output-transforms 1 \
-        --output [ $TEMPLATE_DIR/REG_INPUT_TO_TEMP_ , 1 , 1 ] \
-        --interpolation BSpline[4] \
-        --use-histogram-matching 1 \
-        --winsorize-image-intensities [ 0.005,0.995 ] \
-        --masks [ $TEMPLATE_DIR/OASIS_registrationMask.nii.gz , 1 ] \
-        --initial-moving-transform $TEMPLATE_DIR/REG_INPUT_TO_TEMP_INIT.mat \
-        --transform Rigid[ 0.1 ] \
-        --metric Mattes[ $TEMPLATE_DIR/OASIS_T1w.nii.gz , $input_file , 1 , 32 , Regular , 0.25 ] \
-        --convergence [ 1000x500x250,1e-6,10 ] \
-        --shrink-factors 4x2x1 \
-        --smoothing-sigmas 3x2x1vox \
-        --transform Affine[ 0.1 ] \
-        --metric Mattes[ $TEMPLATE_DIR/OASIS_T1w.nii.gz , $input_file , 1 , 32 , Regular , 0.25 ] \
-        --convergence [ 1000x500x250,1e-6,10 ] \
-        --shrink-factors 4x2x1 \
-        --smoothing-sigmas 3x2x1vox
-
-    echo "  ${bold} 1. Mapped to template.    ${normal}"
-    echo "--------------------------------------------------------------------------------"
-
-    ################################################################################
-    #
-    # APPLY TRANSFORMS
-    #
-    ################################################################################
-
     ${ANTSPATH}/antsApplyTransforms \
         --dimensionality 3 \
         --interpolation GenericLabel \
@@ -288,9 +222,14 @@ else
 
 fi
 
+################################################################################
+#
+# APPLY MASK
+#
+################################################################################
 ${ANTSPATH}/ImageMath \
     3 \
-    $OUTPUT_NAME \
+    ${OUTPUT_NAME} \
     m \
     $input_file \
     $OUTPUT_MASK_NAME
@@ -308,7 +247,8 @@ nettime0=$(expr $end_time0 - $start_time0)
 ################################################################################
 
 rm $TEMPLATE_DIR/REG_INPUT_TO_TEMP_*.*
-
+echo "  ${bold} 4. Clean-up completed.    ${normal}"
+echo "--------------------------------------------------------------------------------"
 ################################################################################
 #
 # DISPLAY DONE
